security:
    encoders:
        Dosi\AuthBundle\Security\Core\User\LdapUser: plaintext

    role_hierarchy:
        ROLE_ADMIN:       [ROLE_USER, ROLE_SONATA_ADMIN]
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        ldap:
            id: dosi_ldap.security.user.provider

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            provider: ldap
            sso:
                manager: admin_sso
                login_action: false
                logout_action: false
                create_users: false
                default_target_path: /index
            logout: true
            anonymous: true

    access_control:
        - { path: ^/accueil, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login_check, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/co, roles: ROLE_ADMIN }
